### ISSUE TITLE
Stylegan inversion 

### ISSUE THREAD

**Issue by IvanBarabanau** [HideUnderBush/UI2I_via_StyleGAN2#4]
Hi!

According to your paper, it takes about a second to invert an image to its latent representation: "...and another 0.8 − 1 s for the inversion process". However, in your current implementation it is an iterative optimization process, which takes more than a minute with the default settings. Could you, please, clarify how do you successfully accomplish the inversion task within 1 second?

**Comment by HideUnderBush** [comment]
Sorry for the confusion caused, that should be a typo, it is actually around 1 min for an image with a size of 1024x1024. We'll correct it soon in the paper
