### ISSUE TITLE
no module named dnnlib.tflib.ops

### ISSUE THREAD

**Issue by visonpon** [HideUnderBush/UI2I_via_StyleGAN2#6]
Hi @HideUnderBush, thanks for your great work, and when I try to use it, I encounter some problems.
When I use `python closed_from _factorization.py`, I got a` RuntimeError: no default TensorFlow session found. please call dnnlib.init_tf()`, then I do like it says, call dnnlin.init_tf() before tf.get_default_session(), but got no module error as above.
Hope you can help, thanks~

**Comment by FlashlightET** [comment]
Help

**Comment by vin-ni** [comment]
+1 :)
